ProjectionView.1/Models/DashboardDefaultView.cs
namespace ProjectionView._1 {
	public sealed class DashboardDefaultView :
		ViewBase {
		public int EmployeesCount { get; set; }
		public int JobsCount { get; set; }
	}
}

ProjectionView.1/Models/EmployeeEditView.cs
using System.Collections.Generic;
using ProjectionView.Data;

namespace ProjectionView._1 {
	public sealed class EmployeeEditView :
		ViewBase {
		public Employee Employee { get; set; }
		public IList<Job> Jobs { get; set; }
	}
}

ProjectionView.1/Models/EmployeesListView.cs
using System.Collections.Generic;
using ProjectionView.Data;

namespace ProjectionView._1 {
	public sealed class EmployeesListView :
		ViewBase {
		public IList<Employee> Employees { get; set; }
	}
}

ProjectionView.1/Models/JobAddOrEditForm.cs
namespace ProjectionView._1 {
	public sealed class JobAddOrEditForm {
		public int? CsrId { get; set; }
		public string Name { get; set; }
		public int? StateId { get; set; }
		public int? StatusId { get; set; }
		public int? TypeId { get; set; }
	}
}

ProjectionView.1/Models/JobAddView.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectionView.Data;

namespace ProjectionView._1 {
	public sealed class JobAddView :
		ViewBase {
		public IList<SelectListItem> CsrsSelectListItems { get; set; }
		public Job Job { get; } = new Job();
		public IList<SelectListItem> StatesSelectListItems { get; set; }
		public IList<SelectListItem> StatusesSelectListItems { get; set; }
		public IList<SelectListItem> TypesSelectListItems { get; set; }
	}
}

ProjectionView.1/Models/JobEditView.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectionView.Data;

namespace ProjectionView._1 {
	public sealed class JobEditView :
		ViewBase {
		public IList<SelectListItem> CsrsSelectListItems { get; set; }
		public Job Job { get; set; }
		public IList<SelectListItem> StatesSelectListItems { get; set; }
		public IList<SelectListItem> StatusesSelectListItems { get; set; }
		public IList<SelectListItem> TypesSelectListItems { get; set; }
	}
}

ProjectionView.1/Models/JobsListView.cs
using System.Collections.Generic;
using ProjectionView.Data;

namespace ProjectionView._1 {
	public sealed class JobsListView :
		ViewBase {
		public IList<Job> Jobs { get; set; }
	}
}

ProjectionView.1/Controllers/DashboardController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectionView.Data;

namespace ProjectionView._1.Controllers {
	public sealed class DashboardController :
		ControllerBase {
		public DashboardController(
			ProjectionViewContext context)
			: base(context) {
		}

		[HttpGet]
		public async Task<IActionResult> Default() {
			return View(new DashboardDefaultView {
				EmployeesCount = await Context.Employees.CountAsync(
					e => e.IsActive),
				JobsCount = await Context.Jobs.CountAsync(),
				SignedInEmployee = await GetSignedInEmployee()
			});
		}
	}
}

ProjectionView.1/Controllers/EmployeesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectionView.Data;

namespace ProjectionView._1.Controllers {
	public sealed class EmployeesController :
		ControllerBase {
		public EmployeesController(
			ProjectionViewContext context)
			: base(context) {
		}

		[HttpGet]
		public async Task<IActionResult> Edit(
			int id) {
			return View(new EmployeeEditView {
				Employee = await Context.Employees.SingleAsync(
					e => e.Id == id),
				Jobs = await Context.Jobs.Where(
					j => j.CsrId == id).ToListAsync(),
				SignedInEmployee = await GetSignedInEmployee()
			});
		}

		[HttpGet]
		public async Task<IActionResult> List() {
			return View(new EmployeesListView {
				Employees = await Context.Employees.Include(
					e => e.Jobs).ToListAsync(),
				SignedInEmployee = await GetSignedInEmployee()
			});
		}
	}
}

ProjectionView.1/Controllers/JobsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectionView.Data;

namespace ProjectionView._1.Controllers {
	public sealed class JobsController :
		ControllerBase {
		public JobsController(
			ProjectionViewContext context)
			: base(context) {
		}

		[HttpGet]
		public async Task<IActionResult> Add() {
			return View(new JobAddView {
				CsrsSelectListItems = await GetCsrsSelectListItems(),
				SignedInEmployee = await GetSignedInEmployee(),
				StatesSelectListItems = await GetStatesSelectListItems(),
				StatusesSelectListItems = await GetStatusesSelectListItems(),
				TypesSelectListItems = await GetTypesSelectListItems()
			});
		}

		[HttpPost]
		public async Task<IActionResult> Add(
			JobAddOrEditForm job) {
			var jobEntity = new Job {
				CsrId = job.CsrId,
				Name = job.Name,
				StateId = job.StateId,
				StatusId = job.StatusId,
				TypeId = job.TypeId
			};

			await Context.AddAsync(jobEntity);
			await Context.SaveChangesAsync();

			return RedirectToAction("Edit", new {
				id = jobEntity.Id
			});
		}

		[HttpGet]
		public async Task<IActionResult> Edit(
			int id) {
			return View(new JobEditView {
				CsrsSelectListItems = await GetCsrsSelectListItems(),
				Job = await Context.Jobs.SingleAsync(
					j => j.Id == id),
				SignedInEmployee = await GetSignedInEmployee(),
				StatesSelectListItems = await GetStatesSelectListItems(),
				StatusesSelectListItems = await GetStatusesSelectListItems(),
				TypesSelectListItems = await GetTypesSelectListItems()
			});
		}

		[HttpPost]
		public async Task<IActionResult> Edit(
			int id,
			JobAddOrEditForm job) {
			var jobEntity = await Context.Jobs.SingleOrDefaultAsync(
				j => j.Id == id);

			if (jobEntity == null) {
				return RedirectToAction("List");
			}

			jobEntity.CsrId = job.CsrId;
			jobEntity.Name = job.Name;
			jobEntity.StateId = job.StateId;
			jobEntity.StatusId = job.StatusId;
			jobEntity.TypeId = job.TypeId;

			await Context.SaveChangesAsync();

			return RedirectToAction("Edit", new {
				id
			});
		}

		[HttpGet]
		public async Task<IActionResult> List() {
			return View(new JobsListView {
				Jobs = await Context.Jobs.Include(
					j => j.Csr).Include(
					j => j.State).Include(
					j => j.Status).Include(
					j => j.Type).ToListAsync(),
				SignedInEmployee = await GetSignedInEmployee()
			});
		}

		private async Task<IList<SelectListItem>> GetCsrsSelectListItems() {
			return await Context.Employees.Where(
				e => e.IsActive).OrderBy(
				e => e.Name).Select(
				e => new SelectListItem {
					Text = e.Name,
					Value = e.Id.ToString()
				}).ToListAsync();
		}

		private async Task<IList<SelectListItem>> GetStatesSelectListItems() {
			var countries = await Context.Countries.OrderByDescending(
				c => c.Name).Select(
				c => new SelectListGroup {
					Name = c.Name
				}).ToListAsync();

			return await Context.States.Where(
				s => s.IsActive).OrderBy(
				s => s.Name).Select(
				s => new SelectListItem {
					Group = countries.Single(
						c => c.Name == s.Country.Name),
					Text = s.Name,
					Value = s.Id.ToString()
				}).ToListAsync();
		}

		private async Task<IList<SelectListItem>> GetStatusesSelectListItems() {
			return await Context.Statuses.Where(
				s => s.IsActive).OrderBy(
				s => s.Name).Select(
				s => new SelectListItem {
					Text = s.Name,
					Value = s.Id.ToString()
				}).ToListAsync();
		}

		private async Task<IList<SelectListItem>> GetTypesSelectListItems() {
			return await Context.Types.Where(
				t => t.IsActive).OrderBy(
				t => t.Name).Select(
				t => new SelectListItem {
					Text = t.Name,
					Value = t.Id.ToString()
				}).ToListAsync();
		}
	}
}

ProjectionView.1/Views/Dashboard/Default.cshtml
@model ProjectionView._1.DashboardDefaultView
@{
}
<h2>Dashboard</h2>
<table>
	<tr>
		<th>Employees</th>
		<th>Jobs</th>
	</tr>
	<tr>
		<td>@Model.EmployeesCount</td>
		<td>@Model.JobsCount</td>
	</tr>
</table>

ProjectionView.1/Views/Employees/Edit.cshtml
@model ProjectionView._1.EmployeeEditView
@{
}
<h2>@Model.Employee.Name</h2>
<table>
	<tr>
		<th>Name</th>
	</tr>
	@foreach (var j in Model.Jobs) {
		<tr>
			<td>
				<a asp-action="Edit" asp-controller="Jobs" asp-route-id="@j.Id">@j.Name</a>
			</td>
		</tr>
	}
</table>

ProjectionView.1/Views/Employees/List.cshtml
@model ProjectionView._1.EmployeesListView
@{
}
<h2>Employees</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Jobs</th>
	</tr>
	@foreach (var e in Model.Employees) {
		<tr>
			<td>
				<a asp-action="Edit" asp-controller="Employees" asp-route-id="@e.Id">@e.Name</a>
			</td>
			<td>@e.Jobs.Count</td>
		</tr>
	}
</table>

ProjectionView.1/Views/Jobs/Add.cshtml
@model ProjectionView._1.JobAddView
@{
}
<h2>Add a Job</h2>
<form asp-action="Add" method="post">
	<label asp-for="Job.Name"></label>
	<input asp-for="Job.Name" />
	<br />
	<label asp-for="Job.CsrId">CSR</label>
	<select asp-for="Job.CsrId" asp-items="Model.CsrsSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.StateId">State</label>
	<select asp-for="Job.StateId" asp-items="Model.StatesSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.StatusId">Status</label>
	<select asp-for="Job.StatusId" asp-items="Model.StatusesSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.TypeId">Type</label>
	<select asp-for="Job.TypeId" asp-items="Model.TypesSelectListItems">
		<option></option>
	</select>
	<br />
	<br />
	<button>Save</button>
</form>

ProjectionView.1/Views/Jobs/Edit.cshtml
@model ProjectionView._1.JobEditView
@{
}
<h2>@Model.Job.Name</h2>
<form asp-action="Edit" method="post">
	<label asp-for="Job.Name"></label>
	<input asp-for="Job.Name" />
	<br />
	<label asp-for="Job.CsrId">CSR</label>
	<select asp-for="Job.CsrId" asp-items="Model.CsrsSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.StateId">State</label>
	<select asp-for="Job.StateId" asp-items="Model.StatesSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.StatusId">Status</label>
	<select asp-for="Job.StatusId" asp-items="Model.StatusesSelectListItems">
		<option></option>
	</select>
	<br />
	<label asp-for="Job.TypeId">Type</label>
	<select asp-for="Job.TypeId" asp-items="Model.TypesSelectListItems">
		<option></option>
	</select>
	<br />
	<br />
	<button>Save</button>
</form>

ProjectionView.1/Views/Jobs/List.cshtml
@model ProjectionView._1.JobsListView
@{
}
<h2>Jobs</h2>
<table>
	<caption>
		<a asp-action="Add" asp-controller="Jobs">Add a Job</a>
	</caption>
	<tr>
		<th>Name</th>
	</tr>
	@foreach (var j in Model.Jobs) {
		<tr>
			<td>
				<a asp-action="Edit" asp-controller="Jobs" asp-route-id="@j.Id">@j.Name</a>
			</td>
			<td>@j.Csr?.Name</td>
			<td>@j.State?.Name</td>
			<td>@j.Status?.Name</td>
			<td>@j.Type?.Name</td>
		</tr>
	}
</table>

ProjectionView.1/Views/Shared/_Layout.cshtml
@model ProjectionView._1.ViewBase
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />
	<link rel="stylesheet" href="~/styles/default.css" />
	<title>Projection-View Pattern (1)</title>
</head>
<body>
	<p>Hello <a asp-action="Edit" asp-controller="Employees" asp-route-id="@Model.SignedInEmployee.Id">@Model.SignedInEmployee.Name</a>!</p>
	<hr />
	<nav>
		<a asp-action="Default" asp-controller="Dashboard">Dashboard</a>
		<a asp-action="List" asp-controller="Jobs">Jobs</a>
		<a asp-action="List" asp-controller="Employees">Employees</a>
	</nav>
	<hr />
	@RenderBody()
	<mini-profiler />
</body>
</html>